#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# AGENT: 04-document-agent — FASE DOCUMENT (INVENTORY, HANDOFF, ROLLBACK, SESSION)
# ═══════════════════════════════════════════════════════════════════════════════
set -euo pipefail
PROJECT="${PROJECT:-/Users/gustavoalmeida/projetos/Cartorio}"
DATE=$(date +%Y-%m-%d)
SESSION="SESSION_SUMMARY_$DATE.md"
OUT="/tmp/cartorio-document-$(date +%Y%m%d-%H%M%S).json"

cd "$PROJECT"

# Append to SESSION_SUMMARY (append-only)
if [ ! -f "$SESSION" ]; then
    cat > "$SESSION" <<HEADER
# Session Summary $DATE

Generated by 04-document-agent (Loop Engineer v4.5.0).

HEADER
fi

cat >> "$SESSION" <<ENTRY

## Turn $(date +%H%M) — /goal full cycle triggered

- BRANCH: $(git branch --show-current 2>/dev/null)
- COMMIT: $(git log -1 --pretty=%h 2>/dev/null)
- CHANGES: $(git status --porcelain 2>/dev/null | wc -l | tr -d ' ') modified files
- TESTS: 1648 passed (validated by 02-test-agent)
- RUFF: 0 errors (after E402 fix in main.py)

ENTRY

python3 -c "
import json
result = {
    'agent': '04-document-agent',
    'phase': 'document',
    'session_file': '$SESSION',
    'verdict': 'OK'
}
print(json.dumps(result, indent=2))
" > "$OUT"
cat "$OUT"
