import json
import sys
from pathlib import Path

try:
    from openapi_spec_validator import validate
except ImportError:
    print("[ERROR] openapi-spec-validator not installed. Run: uv pip install openapi-spec-validator", file=sys.stderr)
    sys.exit(1)

# A path from the backend folder to the snapshots folder. The snapshot script is run from the root directory but when we run this script we run from backend, but `make openapi-check` calls `cd backend && uv run python ../scripts/validate_openapi_spec.py`. So the snapshot file `snapshots/openapi.current.json` generated by `scripts/openapi_snapshot.py` is at the root directory. Therefore from `backend/` directory, it is `../snapshots/openapi.current.json`.
CURRENT = Path("../snapshots/openapi.current.json")

def main():
    if not CURRENT.exists():
        print(f"[ERROR] Snapshot file not found: {CURRENT}", file=sys.stderr)
        sys.exit(1)

    spec = json.loads(CURRENT.read_text())

    try:
        validate(spec)
        print("[OK] OpenAPI specification is valid")
        return 0
    except Exception as e:
        print(f"[ERROR] OpenAPI validation failed:\n{e}", file=sys.stderr)
        return 1

if __name__ == "__main__":
    sys.exit(main())
