"""Add client notification fields

Revision ID: 2026_06_25_0014
Revises: 2026_06_25_0013
Create Date: 2026-06-25 00:00:00.000000

Adiciona campos de notificacao na tabela clientes:
- telegram_chat_id
- whatsapp_number
- email_notifications (bool, default true)
- sms_notifications (bool, default true)
- preferred_contact_method

LGPD: campos sao nullable ate consentimento explicito do cliente.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2026_06_25_0014'
down_revision: Union[str, None] = '2026_06_25_0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('sms_notifications', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('preferred_contact_method', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('preferred_contact_method')
        batch_op.drop_column('sms_notifications')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('whatsapp_number')
        batch_op.drop_column('telegram_chat_id')
    # ### end Alembic commands ###